### ISSUE TITLE
Orphaned on CRAN

### ISSUE THREAD

**Issue by ms609** [ropensci/bibtex#28]
I see that this package has recently become listed on CRAN as orphaned – which is a real shame as I use it often.  Is this a temporary blip or has maintenance of the package been discontinued?

**Comment by llrs** [comment]
Maybe the problem is with the email, as the description on the Github points to r-enthusiasts.com/ which doesn't seem to exists any longer.

**Comment by coatless** [comment]
@ms609 temporary. rOpenSci is adopting the package.

**Comment by ms609** [comment]
Thanks, @ropensci! I wish I had enough capacity to offer to help out.

**Comment by ShixiangWang** [comment]
Is there a solution to put it back to CRAN, many R packages will be dropped due to its status "Orphaned on CRAN". 😭

**Comment by sckott** [comment]
@coatless has taken over and should be submitting a new version soon i think?

**Comment by coatless** [comment]
Howdy folks, CRAN wants all rchk errors taken care of prior to re-listing. The source for `bibtex` is a bit large in _C_. So, it's taking a bit longer than I had anticipated. There are a few rchk errors still.

We should have a candidate that CRAN accepts shortly.

**Comment by duckmayr** [comment]
@coatless I may have a project soon that depends on `bibtex` and would be happy to lend a hand on getting this back in full status on CRAN, though I wouldn't have time to help out until the end of the month

Feel free to let me know what would help / where you need folks to pitch in!

**Comment by dieghernan** [comment]
+1 I think I can also help a little bit on this

**Comment by dieghernan** [comment]
Cross posted https://ropensci.slack.com/archives/C026GCWKA/p1638555261179100

> Hi, Diego Hernangómez speaking, developer of {cffr}. I would like to know the current status of {bibtex}, as it is still orphaned on CRAN with no changes on the source code on the last 14 months. 
 Recently I was updating cffr for incorporating bibtex support and I ended up developing a clon of bibtex on a few lines of base R:
>
> https://github.com/ropensci/cffr/blob/bibtex/R/bibtex.R

@maelle @sckott @mwmclean (RefManageR, reverse dependency)

**Comment by dieghernan** [comment]
Still I would like to request write access to the repo, @maelle

**Comment by dieghernan** [comment]
I planned to start on a new branch and agree the changes. For me it is ok to start with a PR, but the first thing to do IMHO is to create a full test suite for the package in its current state.

I would work on that first while improving my proposal on my fork if you agree

**Comment by coatless** [comment]
Sounds great! I assume you want to continue the discussion in #45?

**Comment by dieghernan** [comment]
Yeah, don't want to clutter this issue, I think is better this way so I can also expand better the proposal

**Comment by maelle** [comment]
:tada: Thanks and congrats @coatless @dieghernan!
