### ISSUE TITLE
GSOC 2021 R project

### ISSUE THREAD

**Issue by coatless** [ropensci/bibtex#37]
Time is slipping away from me on multiple fronts. To ease this, I'm going to add the `bibtex` package as part of GSOC 2021. 

@sckott any issue with being a co-mentor?

**Comment by coatless** [comment]
Add a brief write up here: https://github.com/rstats-gsoc/gsoc2021/wiki/Addressing-bibtex-rchck-errors

**Comment by sckott** [comment]
I'd like to help, but I can't commit to being available for personal reasons
