### ISSUE TITLE
Development environment of contributors?

### ISSUE THREAD

**Issue by matthewwiese** [ropensci/bibtex#41]
Hey all,

I encountered some bumps in the road unrelated to the `rchk` issues that I've been recently looking into, and thought it pertinent to bring up: how do existing contributors develop for `bibtex` locally?

For example, I'm on Ubuntu 20.04, and so my `bison` version is 3.5.1 and `flex` is 2.6.4 - this proved to be a headache when running `regram.sh` to rebuild the lexer and parser C source/headers.

For example, the first line of `src/bibparse.c`:
```C
/* A Bison parser, made by GNU Bison 2.3.  */
```
Suggests that it was built from a version of Bison 15 years old!

I ended up compiling Bison 2.3 from source and modifying `regram.sh` to use that as a temporary workaround. Am I missing something here? How is this package maintained/developed?

**Comment by coatless** [comment]
Gently closing this out as the package no longer uses C.
