### ISSUE TITLE
Direct import into EndNote is not possible

### ISSUE THREAD

**Issue by micwij** [ropensci/bibtex#54]
Hi,

I am using EndNote as a citation manager. Unfortunately I am not able to directly import .bib entries generated with bibtex into EndNote. Currently I import the entries into Zotero, export as .ris from there and reimport into EndNote. Except from a minor issue when using Zotero (see #53 ) this works, but having a direct option to import into EndNote would of course be desirable.

Thanks!

**Comment by coatless** [comment]
So, the `bibtex` package is focused solely on the `.bib` format. Setting things up for proprietary software such as EndNote is out of the scope. You might want to make this a feature request with the EndNote folks.

That said, a quick google search did show a potential way of directly using a `.bib` with EndNote. 

https://intranet.birmingham.ac.uk/as/libraryservices/library/research/endnote/importing-and-exporting.aspx

Suggests using the `bibtex` filter from:

https://endnote.com/downloads/filters/

https://endnote.com/filter_download/bibtex-sample/
